### ISSUE TITLE
WorldGuard 6.1.3 integrated custom flag support.

### ISSUE THREAD

**Issue by mibby** [mewin/WGCustomFlags#20]
WorldGuard 6.1.3 updated to support custom flag registration. Any plans on porting all the custom flag modules to the integrated support?

**Comment by mibby** [comment]
@mewin For example, some old custom flag modules broke either caused by MC 1.10 or the latest WG changes.

```
[04:00:26] [Server thread/INFO]: [WGInstabreakFlag] Enabling WGInstabreakFlag v1.0
[04:00:26] [Server thread/ERROR]: Error occurred while enabling WGInstabreakFlag v1.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.sk89q.worldguard.protection.flags.StateFlag.State.allow
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_92]
	at com.sk89q.worldguard.protection.flags.StateFlag$State.valueOf(StateFlag.java:33) ~[?:?]
	at com.mewin.WGCustomFlags.data.YAMLSaveHandler.castValue(YAMLSaveHandler.java:127) ~[?:?]
	at com.mewin.WGCustomFlags.data.YAMLSaveHandler.loadFlagsForWorld(YAMLSaveHandler.java:104) ~[?:?]
	at com.mewin.WGCustomFlags.WGCustomFlagsPlugin.loadFlagsForWorld(WGCustomFlagsPlugin.java:184) ~[?:?]
	at com.mewin.WGCustomFlags.WGCustomFlagsPlugin.loadAllWorlds(WGCustomFlagsPlugin.java:171) ~[?:?]
	at com.mewin.WGCustomFlags.FlagManager.addCustomFlag(FlagManager.java:70) ~[?:?]
	at com.mewin.WGCustomFlags.WGCustomFlagsPlugin.addCustomFlag(WGCustomFlagsPlugin.java:229) ~[?:?]
	at de.omr.wgibf.listener.BlockDamageListener.<init>(BlockDamageListener.java:47) ~[?:?]
	at de.omr.wgibf.WGInstabreakFlagPlugin.onEnable(WGInstabreakFlagPlugin.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.jar:git-Paper-784]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.jar:git-Paper-784]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.jar:git-Paper-784]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.jar:git-Paper-784]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.jar:git-Paper-784]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.jar:git-Paper-784]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.jar:git-Paper-784]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.jar:git-Paper-784]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.jar:git-Paper-784]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.jar:git-Paper-784]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
[04:00:26] [Server thread/INFO]: [WGInstabreakFlag] Disabling WGInstabreakFlag v1.0
```

**Comment by NathanWolf** [comment]
It seems like WGCustomFlags could be updated to bridge all of the existing plugins that use it to the new system.

I'm not certain though- I started updating it myself but haven't got to testing the changes yet. Let me know if I can help out here, or if you have plans already to do this.
